export const OFFLINE_FEEDBACK_STORAGE_KEY = 'PIXEL_TRACKER_FEEDBACK_OUTBOX';
export const OFFLINE_STATISTICS_FEEDBACK_STORAGE_KEY = 'PIXEL_TRACKER_STATISTICS_FEEDBACK_OUTBOX';
export const OFFLINE_QUESTION_RESPONSE_STORAGE_KEY = 'PIXEL_TRACKER_QUESTION_RESPONSES';
